# encoding: utf-8
# Generated by Django 1.9.5 on 2017-10-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addressinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=50, verbose_name='省份')),
                ('cityName', models.CharField(max_length=50, verbose_name='城市名')),
                ('countyName', models.CharField(max_length=50, verbose_name='区域名')),
                ('detailInfo', models.CharField(max_length=50, verbose_name='具体地址')),
                ('postalCode', models.CharField(max_length=50, verbose_name='邮编')),
                ('telNumber', models.CharField(max_length=50, verbose_name='联系电话')),
                ('W_id', models.CharField(max_length=50, verbose_name='ID')),
                ('nationalCode', models.CharField(max_length=50, verbose_name='国际编码')),
                ('userName', models.CharField(max_length=50, verbose_name='联系人')),
            ],
            options={
                'verbose_name_plural': '地址信息',
                'verbose_name': '地址信息',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '品类',
                'verbose_name': '品类',
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '颜色',
                'verbose_name': '颜色',
            },
        ),
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '款式',
                'verbose_name': '款式',
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.CharField(max_length=50, verbose_name='商品id')),
                ('design', models.CharField(max_length=50, verbose_name='款式id')),
                ('category', models.CharField(max_length=50, verbose_name='品类id')),
                ('color', models.CharField(max_length=50, verbose_name='颜色id')),
                ('size', models.CharField(max_length=50, verbose_name='尺码id')),
                ('amount', models.CharField(max_length=50, verbose_name='数量')),
                ('goodinfo', models.TextField(max_length=50, verbose_name='商品详情')),
                ('frontpic', models.CharField(max_length=50, verbose_name='正面图片')),
                ('oppositpic', models.CharField(max_length=50, verbose_name='反面图片')),
                ('Name', models.CharField(max_length=50, verbose_name='商品名')),
                ('nowprice', models.CharField(max_length=50, verbose_name='现价')),
                ('pastprice', models.CharField(max_length=50, verbose_name='原价')),
                ('ontime', models.CharField(max_length=50, verbose_name='上架时间')),
                ('offtime', models.CharField(max_length=50, verbose_name='下架时间')),
            ],
            options={
                'verbose_name_plural': '商品信息',
                'verbose_name': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=50, verbose_name='订单号')),
                ('goodsid', models.CharField(max_length=50, verbose_name='商品表id')),
                ('picid', models.CharField(max_length=50, verbose_name='图片合成表id')),
                ('addressid', models.CharField(max_length=100, verbose_name='地址表id')),
                ('userid', models.CharField(max_length=50, verbose_name='用户信息表id')),
                ('riqi', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('expressidnum', models.CharField(max_length=50, verbose_name='快递单号')),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'verbose_name': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='picmake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontx', models.CharField(max_length=50, verbose_name='正坐标x')),
                ('fronty', models.CharField(max_length=50, verbose_name='正坐标y')),
                ('frontpic', models.CharField(max_length=50, verbose_name='正面图')),
                ('oppositex', models.CharField(max_length=100, verbose_name='反坐标x')),
                ('oppositey', models.CharField(max_length=50, verbose_name='反坐标y')),
                ('oppositepic', models.CharField(max_length=50, verbose_name='反面图')),
                ('frontmakepic', models.CharField(max_length=50, verbose_name='正面合成图')),
                ('oppositemakepic', models.CharField(max_length=50, verbose_name='反面合成图')),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'verbose_name': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '尺码',
                'verbose_name': '尺码',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
            },
        ),
    ]
