# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhouxinyuan11', '0002_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='addressid',
            field=models.IntegerField(max_length=100, verbose_name='地址表id'),
        ),
    ]
