# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-24 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addressinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=50, verbose_name='省份')),
                ('cityName', models.CharField(max_length=50, verbose_name='城市名')),
                ('countyName', models.CharField(max_length=50, verbose_name='区域名')),
                ('detailInfo', models.CharField(max_length=50, verbose_name='具体地址')),
                ('postalCode', models.CharField(max_length=50, verbose_name='邮编')),
                ('telNumber', models.CharField(max_length=50, verbose_name='联系电话')),
                ('userid', models.CharField(default='', max_length=50, verbose_name='用户id')),
                ('nationalCode', models.CharField(max_length=50, verbose_name='国际编码')),
                ('userName', models.CharField(max_length=50, verbose_name='联系人')),
            ],
            options={
                'verbose_name': '地址信息',
                'verbose_name_plural': '地址信息',
            },
        ),
        migrations.CreateModel(
            name='BuyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('goodid', models.CharField(max_length=50, verbose_name='商品id')),
                ('pic', models.CharField(default='', max_length=50, verbose_name='商品图片')),
                ('Name', models.CharField(default='', max_length=50, verbose_name='商品名')),
                ('price', models.CharField(default='', max_length=50, verbose_name='价格')),
            ],
            options={
                'verbose_name': '历史记录',
                'verbose_name_plural': '历史记录',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('oldgoodsid', models.CharField(default='', max_length=50, verbose_name='原商品表id')),
                ('newgoodsid', models.CharField(default='', max_length=50, verbose_name='新商品表id')),
                ('oldamount', models.CharField(default='', max_length=50, verbose_name='原数量')),
                ('newamount', models.CharField(default='', max_length=50, verbose_name='新数量')),
                ('expressidnum', models.CharField(default='', max_length=5, verbose_name='快递单号')),
            ],
            options={
                'verbose_name': '换货',
                'verbose_name_plural': '换货',
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('goodsid', models.CharField(max_length=50, verbose_name='商品表id')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50, verbose_name='订单ID')),
                ('text', models.CharField(max_length=200, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('goodsid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('stars', models.CharField(max_length=50, verbose_name='星级')),
                ('feedback', models.CharField(max_length=50, verbose_name='反馈')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('goodsid', models.CharField(default='', max_length=50, verbose_name='商品表id')),
                ('answer', models.CharField(default='', max_length=50, verbose_name='回复')),
            ],
            options={
                'verbose_name': '信息反馈',
                'verbose_name_plural': '信息反馈',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.CharField(max_length=50, verbose_name='商品id')),
                ('amount', models.CharField(max_length=50, verbose_name='数量')),
                ('goodinfo', models.TextField(max_length=50, verbose_name='商品详情')),
                ('pic', models.ImageField(upload_to='media', verbose_name='商品图片')),
                ('Name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.CharField(max_length=50, verbose_name='现价')),
                ('purchase', models.CharField(default='', max_length=50, verbose_name='购买人数')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('goodsid', models.CharField(max_length=50, verbose_name='商品表id')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
            ],
            options={
                'verbose_name': '历史记录',
                'verbose_name_plural': '历史记录',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=50, verbose_name='订单号')),
                ('goodsid', models.CharField(max_length=50, verbose_name='商品id')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('expressidnum', models.CharField(max_length=50, verbose_name='快递单号')),
                ('amount', models.CharField(default='', max_length=50, verbose_name='数量')),
                ('addressid', models.CharField(default='', max_length=50, verbose_name='地址表id')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('goodsid', models.CharField(max_length=50, verbose_name='商品表id')),
                ('amount', models.CharField(max_length=50, verbose_name='数量')),
            ],
            options={
                'verbose_name': '退货',
                'verbose_name_plural': '退货',
            },
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('goodsid', models.CharField(max_length=50, verbose_name='商品id')),
                ('amount', models.CharField(max_length=1000, verbose_name='数量')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
